In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7316, 8412, 4718, 2858],
 [7316, 8412, 4718, 5863],
 [7316, 6755, 4718, 684],
 [7265, 8713, 8322, 6831, 2729],
 [7265, 8713, 8322, 6831, 250],
 [4038, 7316, 4477, 4718, 2563],
 [948, 8560, 2834, 6831]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7316 8412 4718 2858]
 [   0    0    0    0 7316 8412 4718 5863]
 [   0    0    0    0 7316 6755 4718  684]
 [   0    0    0 7265 8713 8322 6831 2729]
 [   0    0    0 7265 8713 8322 6831  250]
 [   0    0    0 4038 7316 4477 4718 2563]
 [   0    0    0    0  948 8560 2834 6831]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 271ms/step


array([[[ 1.45537369e-02, -4.38536778e-02, -4.77674268e-02,
          2.26111077e-02, -2.70665530e-02, -4.66544405e-02,
         -6.13547489e-03, -2.62301043e-03, -4.88648675e-02,
          2.96785943e-02],
        [ 1.45537369e-02, -4.38536778e-02, -4.77674268e-02,
          2.26111077e-02, -2.70665530e-02, -4.66544405e-02,
         -6.13547489e-03, -2.62301043e-03, -4.88648675e-02,
          2.96785943e-02],
        [ 1.45537369e-02, -4.38536778e-02, -4.77674268e-02,
          2.26111077e-02, -2.70665530e-02, -4.66544405e-02,
         -6.13547489e-03, -2.62301043e-03, -4.88648675e-02,
          2.96785943e-02],
        [ 1.45537369e-02, -4.38536778e-02, -4.77674268e-02,
          2.26111077e-02, -2.70665530e-02, -4.66544405e-02,
         -6.13547489e-03, -2.62301043e-03, -4.88648675e-02,
          2.96785943e-02],
        [-1.02481134e-02,  2.36385353e-02,  1.76912807e-02,
          3.57227661e-02,  3.95324714e-02, -2.75005344e-02,
         -3.50309610e-02,  3.14625613e-02, -3.734450

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7316, 8412, 4718, 2858])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 78ms/step


array([[ 0.01455374, -0.04385368, -0.04776743,  0.02261111, -0.02706655,
        -0.04665444, -0.00613547, -0.00262301, -0.04886487,  0.02967859],
       [ 0.01455374, -0.04385368, -0.04776743,  0.02261111, -0.02706655,
        -0.04665444, -0.00613547, -0.00262301, -0.04886487,  0.02967859],
       [ 0.01455374, -0.04385368, -0.04776743,  0.02261111, -0.02706655,
        -0.04665444, -0.00613547, -0.00262301, -0.04886487,  0.02967859],
       [ 0.01455374, -0.04385368, -0.04776743,  0.02261111, -0.02706655,
        -0.04665444, -0.00613547, -0.00262301, -0.04886487,  0.02967859],
       [-0.01024811,  0.02363854,  0.01769128,  0.03572277,  0.03953247,
        -0.02750053, -0.03503096,  0.03146256, -0.0373445 ,  0.00364722],
       [ 0.04903698,  0.00152083,  0.00450485,  0.03319167, -0.03228085,
         0.02343348,  0.00346024,  0.02819956, -0.00896834, -0.02768102],
       [ 0.00069316,  0.02437237, -0.025348  , -0.0394081 ,  0.0258813 ,
         0.04512705, -0.04402376, -0.00100373